### ISSUE TITLE
My classroom does not have the option add course

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-classroom#113]
Hello!
My classroom:
http://algo2-undav.classroom.mumuki.io/#/courses
Is not showing the option to add a course.
See image here:
http://imgur.com/a/yKaSw
What is going on?

**Comment by flbulgarelli** [comment]
Hi @estefaniamiguel, I assume you have already solved this issue right?

**Comment by flbulgarelli** [comment]
Closing
