### ISSUE TITLE
Error logging to Classroom. Callback URL Mismatch

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-classroom#12]
mumuki
Oops!, something went wrong

Callback URL mismatch.
The url "http://pdep-utn.clasroom.mumuki.io/auth/auth0/callback" is not in the list of allowed callback URLs: http://*.mumuki.io/auth/auth0/callback, http://*.stg.mumuki.io/auth/auth0/callback.
Please go to the Application Settings page and make sure you are sending a valid callback url from your application.

**Comment by faloi** [comment]
Mmmm, doesn't happen to me. Perhaps you missed an `s` in clas**s**room?

**Comment by flbulgarelli** [comment]
Yup. You must have typed the wrong url :smile:
