### ISSUE TITLE
Gulp watch execution time is prohibitive on Vagrant installation

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-classroom#125]
The task `dev:watch` is reeeeeeeaaly slow (~10 minutes), causing the `devstart` to run for a lot of time before seeing the code running.

Some screenshots taken on the same machine:

**With Vagrant**
![image](https://user-images.githubusercontent.com/1585835/28433338-819b2d1a-6d8b-11e7-8e09-ad865a6e39de.png)

**Without Vagrant**
![image](https://user-images.githubusercontent.com/1585835/28433400-b1780f76-6d8b-11e7-94d9-d67e373befd7.png)

**Comment by faloi** [comment]
Perhaps using `nfs` for the synced folder could speed up things, as seen here: http://rdallasgray.github.io/blog/2015/08/03/lessons-in-developing-with-vagrant/

I tried it but `mount` fails when trying to reach the IP of the host machine.

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mumuki-platform/issues/305

**Comment by flbulgarelli** [comment]
Won't fix. Devinstaller has been deprecated https://github.com/mumuki/mumuki-classroom/commit/bfe5a886bebcd16b2ca2262caa034fadb8f952cc. Now the prefered way to run this code is using a standard local node installation.
