### ISSUE TITLE
Manual evaluation window is taking too long to load

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-classroom#141]
Simply click on _manual evaluation_ button and wait until it loads - try it in an incognito window.

**Comment by fedescarpa** [comment]
I can't reproduce this issue. I tried in my chrome, firefox and safari (incognito and normal window)

Maybe it is a problem tha happens only with old versions.

**Comment by fedescarpa** [comment]
Can you check it @flbulgarelli ?

**Comment by flbulgarelli** [comment]
Couldn't reproduce
