### ISSUE TITLE
Identify students whose results need to be reviewed 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-classroom#187]
We need to be able to filter students whose success rate is close - above or under - to the target approval percentage, in order to quickly find false negatives and false positives. 

Depends on https://github.com/mumuki/mumuki-classroom/issues/186

**Comment by flbulgarelli** [comment]
It would be nice to have an extra column with this information here: https://github.com/mumuki/mumuki-classroom-api/issues/141

**Comment by luchotc** [comment]
@flbulgarelli An extra column with what information? Or did you mean to include this filter in the reports as well?

Also, what does close means? ±1?

**Comment by flbulgarelli** [comment]
> @flbulgarelli An extra column with what information? Or did you mean to include this filter in the reports as well?

I was expecting both: a filter and also a column in the report.

**Comment by flbulgarelli** [comment]
> Also, what does close mean? ±1?

Not sure, surprise me :stuck_out_tongue: But I expect something like ~15% or the closest non-zero integer to the approval condition.

**Comment by luchotc** [comment]
What do you prefer? The option that you mentioned above, or just using that value as default in that filter?

And about this: 

> I was expecting both: a filter and also a column in the report.

What information should the column have?
