### ISSUE TITLE
Deberiamos poder tener la misma guia para distintos examenes en distintos cursos

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-classroom#207]
Hoy en día no puedo crear un examen en un curso si otro curso ya está usando la misma guía como exámen.

**Comment by flbulgarelli** [comment]
Cerrando. Esto es complejo y no vale la pena, porque tener un examen general para varios cursos impediría que por ejemplo el equipo creador pueda hacer modificaciones a alguno de ellos en tiempo de ejecución en función de situaciones particulares del aula.
