### ISSUE TITLE
Automate deployment of existing instances

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-classroom#40]
We could have another repository with the built code and setup Travis there to deploy to Heroku. Also, we should keep the list of existing instances somewhere.

@flbulgarelli @fedescarpa any better ideas?

**Comment by faloi** [comment]
Travis supports [deploying to multiple providers](http://docs.travis-ci.com/user/deployment/#Deploying-to-Multiple-Providers), but I think we should keep the list of instances private. Perhaps a private repo for built code could do the trick.

**Comment by flbulgarelli** [comment]
Since now classroom is multitenant, this is not an issue anymore
