### ISSUE TITLE
Permissions: grant at Course level

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-classroom#6]
When in a classroom, I can see other courses, not just mine.
This is not necessarily an issue. BUT I want to add 8 assistant teachers to the classroom, for them to be able to follow the progress of their assigned students.
Perhaps adding permissions at course level would make this less a mess - everyone seeing everything. Perhaps the creator of a course could have permissions to grant permissions whithin this course.
However, right now I can live with the current status.

**Comment by flbulgarelli** [comment]
Hi @asanzo, thanks for the report. 

Fortunately this has been already implemented. We assigned full organization permissions to you, but we can assign finer-grained permissions to users, so that they can only access certain courses or edit specific guides.

**Comment by flbulgarelli** [comment]
PS: just you need to let us know and we will assign the right permissions. 

In a medium-term future, you will be able to do that by yourself, too :wink:

**Comment by asanzo** [comment]
Huge flow of love for you, boys.
