### ISSUE TITLE
Guide solutions shows too many students - Not just from chosen course

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-classroom#7]
As for today, http://pdep-utn.classroom.mumuki.io/#/pdep-utn/2016-man-ju/mumuki-guia-funcional-valores-y-funciones should show just tsandler's solutions, as he is the only enroled student in the ourse. However, every student from the Summer course shows up in the list.
BUG!

**Comment by flbulgarelli** [comment]
Fixed.
